# Generated by Django 2.1.4 on 2018-12-15 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('staff', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='+90 ', max_length=14)),
                ('address', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
