# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff',
            field=models.CharField(default='', max_length=30),
        ),
    ]
