# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-11 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181211_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff',
            field=models.CharField(default='Doctor', max_length=20),
        ),
    ]
